create table person(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	fio varchar(100),
	email varchar(100),
	phone BIGINT,
	primary key(id)
);

create table user_address(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	address varchar(30),
	phone BIGINT,
	primary key(id)
);

create table pattern(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name_pattern varchar(30),
	iban int,
	goal varchar(20),
	address BIGINT,
	primary key(id),
	FOREIGN KEY(address) REFERENCES user_address(id)
);

create table pay( 
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	id_pattern BIGINT,
	cart_number BIGINT,
	suma BIGINT,
	status varchar(20),
	date_creation timestamp,
 	date_change timestamp,
 	FOREIGN KEY(id_pattern) REFERENCES pattern(id)
);

select * from person;
select * from user_address;
select * from pattern;
select * from pay;

drop table person;
drop table user_address;
drop table pattern;
drop table pay;